<?php

/**
 * Example of the campaignContent() API call
 * @link http://apidocs.mailchimp.com/api/1.3/campaigncontent.func.php
 * @author Ben Tadiar <ben@handcraftedbyben.co.uk>
 */

// Require the bootstrap
require_once(dirname(__FILE__) . '/../bootstrap.php');

// Retrieve the campaign manager object
$campaignManager = $mailchimp->getManager('Campaign');

$orderID = ''; // Unique order ID, generated by your ecommerce platform
$campaignID = ''; // Campaign ID (mc_cid) to track order with
$emailID = ''; // Email ID (mc_eid) to attach order to
$storeID = ''; // Unique, user-defined ID for the store sending the order in

// Create an ecommerce order object
$order = new \MailChimp\Object\EcommerceOrder($orderID, $campaignID, $emailID, $storeID);

// Define item options
$productID = 123;
$productName = 'ItemOne';
$categoryID = 456;
$categoryName = 'Miscellaneous';
$unitPrice = 100.00;
$quantity = 1;

// Add an item using the options above
$order->addItem($productID, $productName, $categoryID, $categoryName, $unitPrice, $quantity);

// Set shipping and tax (to be calculated by your ecommerce platform)
$order->setShipping(10.00);
$order->setTax(15.00);

// Attach the order to 
$ecommAdd = $campaignManager->campaignEcommOrderAdd($order);

// Dump the output
var_dump($ecommAdd);
